### ISSUE TITLE
Error fetching because apt-key is deprecated on Ubuntu 22.04 jammy

### ISSUE THREAD

**Issue by markfickett** [humio/ansible-java#18]
I tried installing using this role. I installed the role with `ansible-galaxy install humio.java`.

I'm on Ubuntu:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

The error was:

"Error fetching key 27BC0C8CB3D81623F59BDADCB1998361219BD9C9 from keyserver: keyserver.ubuntu.com", "rc": 1, "stderr": "Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).\ngpg: key B1998361219BD9C9: public key \"Azul Systems, Inc. (Package signing key.)

A pattern for solving a similar problem is like this:
```
       - name: Add OpenHab GPG key
         ansible.builtin.get_url:
           url: https://openhab.jfrog.io/artifactory/api/gpg/key/public
           dest: /etc/apt/trusted.gpg.d/openhab.asc
       - name: Add OpenHab apt source
         ansible.builtin.apt_repository:
           repo: "deb [signed-by=/etc/apt/trusted.gpg.d/openhab.asc] https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable main"
           state: present
       - name: Install OpenHab apt package
         ansible.builtin.apt:
           # Setting update_cache: yes does not seem necessary; apt_repository may take care of it.
           # This install also sets up an openhab user.
           name: openhab
```

**Comment by markfickett** [comment]
Here's what worked for me:

```
       - name: Add AzulZulu GPG key
         ansible.builtin.get_url:
           url: https://repos.azul.com/azul-repo.key
           dest: /etc/apt/trusted.gpg.d/azul-repo.asc
       - name: Add AzulZulu apt source
         ansible.builtin.apt_repository:
           repo: "deb [signed-by=/etc/apt/trusted.gpg.d/azul-repo.asc] https://repos.azul.com/zulu/deb stable main"
           state: present
       - name: Install AzulZulu JDK
         ansible.builtin.apt:
           # installs to /usr/lib/jvm/zulu11/bin/java
           name: zulu11-jdk
       - name: Select installed Java
         community.general.alternatives:
           name: java
           path: /usr/lib/jvm/zulu11/bin/java
```
